### ISSUE TITLE
"Unreachable/Permission Denied" Trouble with Vultr.com ('easy' to correct?...please help???)

### ISSUE THREAD

**Issue by bondbeau** [jlund/streisand-discussions#93] opened 2018-02-04 03:49 UTC
Hello,

Please assist someone who is  'hopeful' but quite inexperienced?:

Message from terminal is;
fatal: [207.246.xxx.xxx]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Permission denied (publickey,password).\r\n", "unreachable": true}
	to retry, use: --limit @/home/user/streisand/playbooks/existing-server.retry

Running Streisand on Other Providers (Advanced);
The server must be accessible using the $HOME/id_rsa SSH Key, and root is used as the connecting user by default. If your provider requires you to SSH with a different user than root (**e.g. ubuntu**) specify the ANSIBLE_SSH_USER environmental variable (e.g. ANSIBLE_SSH_USER=ubuntu) when you run ./streisand.

To my very limited understanding, I interpret this fault to mean that Ubuntu requires a different named user than "root", or a different variable in the string/command, if one want to SSH to that server, and that the ANSIBLE environmental variables allow for that when one runs the ./streisand command in terminal. If that doesn't happen, one gets the "permission denied" response like I did.

Can someone please tell me 'exactly' how to run the ansible/streisand variable so that the SSH is not rejected (if that is what is happening)? I did look a great deal on the web, but couldn't find anything helpful, that I could understand.

Thanks so kindly for your attention!

BB

**Comment by cpu** [comment] 2018-02-05 18:42
Hi @bondbeau,

> Please assist someone who is 'hopeful' but quite inexperienced?:

Happy to help :-) We were all inexperienced once!

> To my very limited understanding, I interpret this fault to mean that Ubuntu requires a different named user than "root", or a different variable in the string/command, if one want to SSH to that server,

That's not quite right. This isn't the cause of the problem you're having with Vultr but I'll explain anyway for background. Some cloud providers (not Vultr) don't enable SSH to the root user of the server by default and instead expect users to connect via an alternative user they create (usually named `ubuntu`) and then become root by using `sudo`. In _that_ case, Streisand needs to know that it shouldn't try to use `root` directly.

> Can someone please tell me 'exactly' how to run the ansible/streisand variable so that the SSH is not rejected (if that is what is happening)? 

My first advice for you is to consider not using Vultr. Streisand _can_ be made to work with this provider but your life will be a lot easier if you use DigitalOcean, Linode, AWS, or Google Cloud. For these providers Streisand can create the server for you and make sure that SSH access is set up properly.

If you're 100% dead set on using Vultr then what you need to do is make sure that you have your SSH public key configured in the Vultr control panel and associated with the server you create. I'll need more information to help you do this:

1. What operating system are you using on the machine running Streisand?
1. Do you have a `~/.ssh/id_rsa.pub` file on that machine?
1. Do you have a SSH key added to [the SSH keys section of the Vultr control panel](https://my.vultr.com/sshkeys/)?

Thanks!

**Comment by bondbeau** [comment] 2018-02-07 03:02
Many apologies for the delay @cpu!,

1. The Streisand OS is Ubuntu 16.04.3 (as a dual-boot, not a VM, with Windows 10).
2. Yes, I made an SSH key and have the "cat ~/.ssh/id_rsa.pub" file on that same machine
3. Yes, I added the public SSH key to Vultr, using "cat ~/.ssh/id_rsa.pub" as the terminal command to create the correct format for Vultr.

Thanks again...eager to try this again with your assistance!

**Comment by nopdotcom** [comment] 2018-02-07 12:37
Do you have the `id_rsa`?

**Comment by bondbeau** [comment] 2018-02-07 19:46
I think you're asking if I have the public key? If so, yes I do have that recorded.

**Comment by nopdotcom** [comment] 2018-02-07 23:33
There are two parts to an SSH key: the public part, and the private part. `id_rsa.pub` is the public part and you can give it to anyone. `id_rsa` is the private part, and it's the only thing that unlocks the public part. You keep the private part secret. 

One problem I've personally had with Vultr: forgetting to actually enable the SSH key I want to use:

![capto_capture 2018-02-07_06-24-19_pm](https://user-images.githubusercontent.com/1357866/35947272-06100b72-0c35-11e8-8b42-6ab51e40a7c3.png)

It's not a very good user interface.

**Comment by bondbeau** [comment] 2018-02-08 00:50
I'm not certain about 'enabling' the SSH key as you mention. What I did was search how to add the key to the site (what command in terminal), and then copied/pasted the result. It seems to have accepted it and it shows up there with the name I gave it. So...I think it's correctly installed, but if it needs enabling or connecting to the instance somehow as well, I've not taken ANY steps to modify the server instance that is started/running. I don't even know how to connect to it...ha. I apologize if there is something else you're asking of me? Do you want/need the public key to help further?

**Comment by cpu** [comment] 2018-02-09 14:12
OK! I think I have a plan of attack we can try :-)

> So...I think it's correctly installed, but if it needs enabling or connecting to the instance somehow as well, I've not taken ANY steps to modify the server instance that is started/running.

You should delete the existing server. Unfortunately there doesn't seem to be a way to add a SSH key to an already running server through the Vultr control panel and since you haven't been able to set up the server yet it should be no issue to delete it and recreate it.

When you recreate the server pay very close attention to **Step 6** on the [**Deploy New Instance**](https://my.vultr.com/deploy/) screen.

At first it will show the SSH key that you added, under the name you added instead of "Noir" (that's my key's name). It's hard to tell, but by default the key is **not selected** for this server:
![An unselected SSH key](https://user-images.githubusercontent.com/292650/36031542-14c56730-0d79-11e8-90d8-e26460ef9bc1.png)

What you need to do is **click your key's name** to enable it. That will make the Step 6 information look like this:
![A selected SSH key](https://user-images.githubusercontent.com/292650/36031592-3f730898-0d79-11e8-9ff0-7cc9d9169131.png)

That will select your SSH key for the server. You can then go ahead and create the new server and try Streisand again.

If you still run into an error, don't fret. We'll know that at least the Vultr side is configured correctly and can go about troubleshooting your SSH client.

**Comment by bondbeau** [comment] 2018-02-09 21:27
1. I don't think I've felt so ignorant in quite a while...I simply did not divine that I had to actually 'select' an SSH key that was already made, as I thought it would already make the connection as long as there weren't multiple SSH's to choose from. Oh my...actually choosing the SSH as part of step 6 (as you indicated), caused a good 10 or 15 minutes of 'Streisand' activity to happen, wherein I added/changed absolutely nothing, except when it stopped and asked if I'd like to add an email address (which I did).

2. Please remain patient with me, as considering my lack above, I'm no doubt do have further requests for assistance now that it seems to have gotten much further along, or has even finished. And to this point...thank you so very much for your time and expertise. I appreciate it greatly!

**Comment by cpu** [comment] 2018-02-09 21:34
@bondbeau :laughing: No need to feel ignorant! Both myself and @nopdotcom have been tripped up by this Vultr user interface decision. It's not intuitive! I'm super happy to hear that you were able to get Streisand to talk to your Vultr instance :tada: :lock: :tada: 

I'm going to close this particular issue since we've resolved the "Unreachable/Permission Denied" problem.

Please feel free to let us know if you have any other problems - the best way is to create a new issue for any follow-up problems so that we can try to maintain a "one problem, one issue" system :-)

**Closed as completed by cpu** 2018-02-09 21:34 UTC

**Comment by bondbeau** [comment] 2018-02-10 01:11
Okay thanks so much! Since the install appeared to complete and I got the generated-docs folder inside the Streisand folder inside the Home folder (and I don't know much of anything about what do do past that), I'll open a separate discussion/issue/problem about what I should do from there.
